# Generated by Django 4.2.1 on 2023-05-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendence',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
