# Generated by Django 4.2.1 on 2023-05-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employeeattendence_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeattendence',
            unique_together=set(),
        ),
    ]
