# Generated by Django 4.2.1 on 2023-05-22 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeeattendence_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeattendence',
            unique_together={('date', 'employee')},
        ),
    ]
